### ISSUE TITLE
Parsing fails on #ifdef within enum definitions

### ISSUE THREAD

**Issue by codenamedj** [robotpy/robotpy-cppheaderparser#16]
I have one enum like this in the header file:

```
typedef enum sample
{
    element 1,
    element 2,
#ifdef 0
    element 3,
    element 4
#endif 
} Example;
```

the parser failed to parse the enum. 
comment with /* */ works though.

**Comment by codenamedj** [comment]
Edit: issue exists for any #ifdef inside enum, not just #ifdef 0

**Comment by virtuald** [comment]
My recommendation to you is use a preprocessor like pcpp to deal with this. This is the approach that I just introduced in [header2whatever](https://github.com/virtuald/header2whatever/commit/a4da4a441dcd00718422cd60d9dd6ab4f23d41f7).

**Comment by virtuald** [comment]
I've added a note to the README and the documentation -- we aren't going to fix any preprocessor related issues and may remove existing preprocessor related code, please use a C++ preprocessor.
