### ISSUE TITLE
Incorrectly parsing inheritance with multiple template arguments

### ISSUE THREAD

**Issue by rainman110** [robotpy/robotpy-cppheaderparser#27]
The following header is not parsed correctly

```C++
template <typename Type>
class XYZ : public MyBaseClass<Type, int>
{
    public:
    XYZ();
};
```

CppHeaderParser detects two base classes ( 1.: MyBaseClass<Type, 2: int>) instead of one templated base class.

**Comment by virtuald** [comment]
That's not terribly surprising, the template support code is really quite terrible! Happy to accept any fixes. It looks like there's a testcase that's pretty close, so it might not be too bad to fix if you're up for it: https://github.com/robotpy/robotpy-cppheaderparser/blob/8ca08c1479afbd59caf7796d671789443d35c018/CppHeaderParser/test/TestSampleClass.h#L674

**Comment by virtuald** [comment]
I've pushed a testcase for this at https://github.com/robotpy/robotpy-cppheaderparser/tree/bug-27, but I don't currently have time to take a further look. It appears the inheritance parsing code just doesn't do templates at all -- which I suspect is probably true elsewhere.

I'm surprised there isn't a reusable function somewhere that just parses type definitions... but the code is really quite messy, so I shouldn't be surprised. :man_shrugging:

**Comment by virtuald** [comment]
I've got a fix for this ready, just have to fix other bugs.

**Comment by virtuald** [comment]
Please give #28 a shot and let me know if that addresses the problem.

**Comment by rainman110** [comment]
Thank you! I'll let you know whether this fixes our problem. :+1:
