### ISSUE TITLE
Add readthedocs site?

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-cppheaderparser#5]
Probably not hard, would be useful. This thing is a bit hard to use since the documentation is mostly non-existant.

**Comment by FreeYourSoul** [comment]
I may start a draft this weekend. It is true that the absence of documentation makes the project hard to be popularized. Which is a shame as it's the only cpp header parser out there.

**Comment by virtuald** [comment]
Fixed in 1300fb522ebe154d4b523d391f970252ff3144e8
