### ISSUE TITLE
Classes not interpreted properly when defined inside #ifdef

### ISSUE THREAD

**Issue by nisarul** [robotpy/robotpy-cppheaderparser#56]
Classes with definitions inside #ifdef-#else-#endif are not parsed properly.
```
#ifdef FEATURE_X
class BaseClass
   : public ClassFtX
#else
class BaseClass
#endif
{
    #something
};
```
Above class is not identified as a class when parsing.

**Comment by auscompgeek** [comment]
Implementing a C preprocessor is largely a non-goal of this project. See also #16 and the note in the readme.

**Comment by virtuald** [comment]
Yes, use a preprocessor.
