### ISSUE TITLE
Bug: Do not support right defined auto return values 

### ISSUE THREAD

**Issue by alexkutsan** [robotpy/robotpy-cppheaderparser#57]
Example:
```python
CppHeaderParser.CppHeader("auto foo() -> int ;", argType="string").functions[0]['rtnType']
```

Expected: `int`
Actual: `auto`

**Comment by virtuald** [comment]
Thanks for the input! I'm planning on dropping this fork of CppHeaderParser soon, so I'm not planning on making this fix to CppHeaderParser.

However, I've rewritten CppHeaderParser from the ground up at https://github.com/robotpy/cxxheaderparser, would love some feedback on how usable it is for your usecase. There are still some usability issues and I'm in the process of working through some of them before an initial release on pypi.

I expect cxxheaderparser doesn't handle this correctly either, but it should be easy to address tonight.

**Comment by alexkutsan** [comment]
I Will try to use  robotpy/cxxheaderparse, thanks!

**Comment by virtuald** [comment]
Fixed in https://github.com/robotpy/cxxheaderparser/pull/2
