### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by improve100** [robotpy/robotpy-cppheaderparser#61]
$ pip install robotpy-cppheaderparser
Requirement already satisfied: robotpy-cppheaderparser in /home/maxsense/.pyenv/versions/3.6.1/lib/python3.6/site-packages/robotpy_cppheaderparser-5.0.11-py3.6.egg (5.0.11)
Requirement already satisfied: ply in /home/maxsense/.pyenv/versions/3.6.1/lib/python3.6/site-packages/ply-3.11-py3.6.egg (from robotpy-cppheaderparser) (3.11)
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/home/maxsense/.pyenv/versions/3.6.1/bin/python3.6 -m pip install --upgrade pip' command.

$ robotpy-cppheaderparser --help
robotpy-cppheaderparser: command not found

**Comment by auscompgeek** [comment]
This is a library for programmatically processing C++ headers using Python. Documentation is available at https://cppheaderparser.readthedocs.io

What are you trying to do?

**Comment by improve100** [comment]
sorry, i misunderstood the the repo function as https://github.com/thibaultmarin/hpp2plantuml the same.
