### ISSUE TITLE
Function Pointer not well parsed.

### ISSUE THREAD

**Issue by Erignik** [robotpy/robotpy-cppheaderparser#66]
I'am using this package to do some info collect in file. h, and find this:
test.h
```C
typedef int U32;
typedef int(*p)(int, int);
```

main,py
```python
import CppHeaderParser
cppHeader = CppHeaderParser.CppHeader('test.h')
print(cppHeader.typedefs)
```
the output show as:
{')': 'int ( * p ) ( int , int', 'U32': 'int'}

U32 is parsed well, but the function pointer var shows upon is not as I expected(the key should be p?). Is this design on purpose?

**Comment by virtuald** [comment]
Yeah, cppheaderparser is pretty bad at dealing with function pointers. Recommend you try https://github.com/robotpy/cxxheaderparser instead; once I migrate my large project to use it I will be dropping maintenance of this project.

**Comment by Erignik** [comment]
I have seen https://github.com/robotpy/cxxheaderparser, but my project need to stay Python2.x. Maybe we can do some optimization: before call function _parse_typedef, do regular expression matching, if it's function pointer, do some data collect, else call _parse_typedef.

**Comment by Erignik** [comment]
I'm going to fix it.

**Comment by Erignik** [comment]
#67
