### ISSUE TITLE
Use OrderedDict for storing things

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-cppheaderparser#7]
From: https://bitbucket.org/senex/cppheaderparser/issues/34/use-ordereddict-for-storing-classes-in

Would allow objects/functions/etc to be iterated in source order.

**Comment by auscompgeek** [comment]
This isn't necessary if you just run it with Python 3.7. :stuck_out_tongue_winking_eye:

**Comment by auscompgeek** [comment]
Given we're not interested in maintaining this package long-term, and there already exists a workaround (use a modern version of Python), closing.
