### ISSUE TITLE
Problem with recognizing struct

### ISSUE THREAD

**Issue by aj-d2020** [robotpy/robotpy-cppheaderparser#70]
Recignize struct as class and don't recognize following class at all
Example:

```
struct s1
struct Struct1
{
  virtual HRESULT fun1r(My_UINT_PTR val, DWORD error) = 0;
  virtual void fun2(My_UINT_PTR val) = 0;
};

class Unrecognized_Class:
  public class1,
  public class2
{
 ....
}

class Recognized_Class:
  public class1,
  public class2
{
 ....
}
```

Unrecognized_Class is not recognized at all

**Comment by virtuald** [comment]
cppheaderparser will only correctly parse valid C/C++ code, the code you posted is invalid:

- the classes don't have trailing semicolons
- struct s1 doesn't have a trailing semicolon

Please validate your code with a real C++ compiler and let me know if CppHeaderParser still has issues.
