### ISSUE TITLE
I can't parse this code ";"

### ISSUE THREAD

**Issue by Bestriverjg** [robotpy/robotpy-cppheaderparser#73]
I can't parse this code when I parse mysql source code:

```
static Sys_var_bool Sys_partial_revokes ( "partial_revokes" , "Access of database objects can be restricted, " "even if user has global privileges granted." , GLOBAL_VAR ( opt_partial_revokes ) , CMD_LINE ( OPT_ARG ) , DEFAULT ( DEFAULT_PARTIAL_REVOKES ) , NO_MUTEX_GUARD , IN_BINLOG , ON_CHECK ( check_partial_revokes ) , ON_UPDATE ( partial_revokes_update ) , 0 , sys_var :: PARSE_EARLY );
```
I'm not familiar with c++ but the python error is indicated here：
```
        if len(nameStack) < 2:  # +++
            if len(nameStack) == 1:
                self["type"] = nameStack[0]
                self["name"] = ""
            else:
                error_print("%s", _stack_)
                assert 0
```

**Comment by Bestriverjg** [comment]
I don't know much about the structure of c++, so I want to ask you about it

**Comment by virtuald** [comment]
That isn't valid C++ as-is, you need a preprocessor to handle the macros. As noted in our README:

> If you need anything complex, you should preprocess the code yourself. You can use the excellent pure python preprocessor [pcpp](https://github.com/ned14/pcpp), or the preprocessing facilities provided by your favorite compiler.
