### ISSUE TITLE
[BUG]: Warning about name after union 

### ISSUE THREAD

**Issue by dyadav7** [robotpy/robotpy-cppheaderparser#76]
### Problem description

The below code gives a warning  :
> [1894] WARN unresolved _myunion

As compiler does not give a warning - there is no need for this warning for _myunion. 
Is there a way to suppres Warning ?

```  
struct myStruct {
     char*   name;
     union   _myunion {
         int   a;
         float b;
      } u;
};
```

### Operating System

Linux

**Comment by virtuald** [comment]
Looks like you could set `[CppHeaderParser.CppHeaderParser.print_warnings](https://github.com/robotpy/robotpy-cppheaderparser/blob/main/CppHeaderParser/CppHeaderParser.py#L72)` to 0. 

It's a stupid warning though, I'd accept a PR fixing it.
